const path = "views/Category/articles/";

const GET_ARTICLES_BY_CATEGORY = path + "GET_ARTICLES_BY_CATEGORY";
const RESET_PAGE = path + "RESET_PAGE";
const GET_ARTICLES_BY_CATEGORY_SUCCESS =
  path + "GET_ARTICLES_BY_CATEGORY_SUCCESS";
const GET_ARTICLES_BY_CATEGORY_ERROR = path + "GET_ARTICLES_BY_CATEGORY_ERROR";

export {
  GET_ARTICLES_BY_CATEGORY_SUCCESS,
  GET_ARTICLES_BY_CATEGORY,
  GET_ARTICLES_BY_CATEGORY_ERROR,
  RESET_PAGE
};
