const path = "views/Home/categoryArticles/";

const GET_CATEGORY_ARTICLES = path + "GET_CATEGORY_ARTICLES";
const GET_CATEGORY_ARTICLES_SUCCESS = path + "GET_CATEGORY_ARTICLES_SUCCESS";
const GET_CATEGORY_ARTICLES_ERROR = path + "GET_CATEGORY_ARTICLES_ERROR";

export {
  GET_CATEGORY_ARTICLES,
  GET_CATEGORY_ARTICLES_SUCCESS,
  GET_CATEGORY_ARTICLES_ERROR
};
