const path = "views/Post/timelines/";

const GET_ARTICLES_BY_TIMELINE_ID = path + "GET_ARTICLES_BY_TIMELINE_ID";
const RESET_PAGE = path + "RESET_PAGE";
const GET_ARTICLES_BY_TIMELINE_ID_SUCCESS =
  path + "GET_ARTICLES_BY_TIMELINE_ID_SUCCESS";
const GET_ARTICLES_BY_TIMELINE_ID_ERROR =
  path + "GET_ARTICLES_BY_TIMELINE_ID_ERROR";

export {
  GET_ARTICLES_BY_TIMELINE_ID_SUCCESS,
  GET_ARTICLES_BY_TIMELINE_ID,
  GET_ARTICLES_BY_TIMELINE_ID_ERROR,
  RESET_PAGE
};
