const path = "views/Tag/articles/";

const GET_ARTICLES_BY_TAG = path + "GET_ARTICLES_BY_TAG";
const RESET_PAGE = path + "RESET_PAGE";
const GET_ARTICLES_BY_TAG_SUCCESS = path + "GET_ARTICLES_BY_TAG_SUCCESS";
const GET_ARTICLES_BY_TAG_ERROR = path + "GET_ARTICLES_BY_TAG_ERROR";

export {
  GET_ARTICLES_BY_TAG_SUCCESS,
  GET_ARTICLES_BY_TAG,
  GET_ARTICLES_BY_TAG_ERROR,
  RESET_PAGE
};
